const masjids = [
  {
    "id": "Masjid_Al-Haram",
    "name": "Masjid Al-Haram",
    "shortDescription": "The holiest mosque in Islam, located in Mecca, Saudi Arabia.",
    "location": "Mecca, Saudi Arabia",
    "religion": "Islam",
    "imageurl": "https://www.shutterstock.com/image-photo/kaaba-masjid-al-haram-mecca-600nw-298483886.jpg",
    "architectureImageURL": "https://static.vecteezy.com/system/resources/previews/025/286/970/non_2x/mecca-saudi-arabia-april-2023-a-beautiful-daytime-view-of-the-interior-of-masjid-al-haram-mecca-free-photo.jpg",
    "templeLogoURL": "https://static.vecteezy.com/system/resources/previews/005/947/957/original/masjid-al-haram-mosque-mecca-saudi-arabia-illustration-icon-free-vector.jpg",
    "briefDescription": "Masjid Al-Haram, also known as the Grand Mosque, surrounds the Kaaba and is the holiest site in Islam.",
    "liveurl": "https://www.youtube.com/embed/moQtMet7F7w?si=vfH0zz1mA_pV_sa4",
    "color": "gold and black"
},
{
    "id": "Al-Masjid_an-Nabawi",
    "name": "Al-Masjid an-Nabawi",
    "shortDescription": "The second holiest mosque in Islam, located in Medina, Saudi Arabia.",
    "location": "Medina, Saudi Arabia",
    "religion": "Islam",
    "imageurl": "https://hajjumrahplanner.com/wp-content/uploads/2017/04/masjid-nabawi.jpg",
    "architectureImageURL": "https://madainproject.com/content/media/collect/masjid_nabawi_interior_11728.jpg",
    "templeLogoURL": "https://w7.pngwing.com/pngs/724/24/png-transparent-al-masjid-an-nabawi-green-dome-mosque-islamic-green-and-brown-mosque-cdr-building-medieval-architecture.png",
    "briefDescription": "Al-Masjid an-Nabawi, also known as the Prophet's Mosque, was established and originally built by the Prophet Muhammad.",
    "liveurl": "https://www.youtube.com/embed/Kt7hKHlArl8?si=J7ZIa0RpaOkVTLZa",
    "color": "green and white"
},
{
    "id": "Al-Aqsa_Mosque",
    "name": "Al-Aqsa Mosque",
    "shortDescription": "The third holiest site in Islam, located in Jerusalem.",
    "location": "Jerusalem",
    "religion": "Islam",
    "imageurl": "https://cdn.pixabay.com/photo/2023/10/20/03/19/mosque-8328077_640.jpg",
    "architectureImageURL": "https://www.shutterstock.com/image-photo/march-15-2017-interior-inside-600nw-689447065.jpg",
    "templeLogoURL": "https://cdn.vectorstock.com/i/500p/08/20/dome-of-the-rock-jerusalem-palestine-gaza-isolated-vector-49090820.jpg",
    "briefDescription": "Al-Aqsa Mosque is part of the Al-Haram Al-Sharif, also known as the Temple Mount, and is a significant place of worship and pilgrimage.",
    "liveurl": "https://www.youtube.com/embed/eVczRbVLpIM?si=e7Gnk5EO9mMk0Fs-",
    "color": "gold"
},
{
    "id": "Sultan_Ahmed_Mosque",
    "name": "Sultan Ahmed Mosque",
    "shortDescription": "Also known as the Blue Mosque, located in Istanbul, Turkey.",
    "location": "Istanbul, Turkey",
    "religion": "Islam",
    "imageurl": "https://www.carwiz.rent/data/public/2019-07/blue_mosque_15db837b846c60.jpg",
    "architectureImageURL": "https://example.com/sultan_ahmed_mosque_architecture.jpg",
    "templeLogoURL": "https://www.shutterstock.com/image-vector/vector-illustration-blue-mosque-istanbul-260nw-1959629446.jpg",
    "briefDescription": "The Sultan Ahmed Mosque, popularly known as the Blue Mosque, is an Ottoman-era historical mosque famous for its blue tiles surrounding its interior walls.",
    "liveurl": "https://www.youtube.com/embed/gnCQ_C6yLh4?si=QVAoFcR2emNxTWf5",
    "color": "blue and white"
},
{
    "id": "Sheikh_Zayed_Mosque",
    "name": "Sheikh Zayed Mosque",
    "shortDescription": "A major mosque in Abu Dhabi and a key place of worship in the UAE.",
    "location": "Abu Dhabi, UAE",
    "religion": "Islam",
    "imageurl": "https://arabiahorizons.com/blog/wp-content/uploads/2020/06/Sheikh-Zayed-Grand-Mosque.jpg",
    "architectureImageURL": "https://visitabudhabi.ae/-/media/project/vad/what-to-see/national-attractions/sheikh-zayed-grand-mosque/sheikh-zayed-grand-mosque/sheikh-zayed-grand-mosque-03.jpg",
    "templeLogoURL": "https://www.shutterstock.com/shutterstock/photos/2393546261/display_1500/stock-vector-abu-dhabi-uae-december-sheikh-zayed-grand-mosque-centre-abu-dhabi-unite-arab-emirates-2393546261.jpg",
    "briefDescription": "The Sheikh Zayed Grand Mosque is one of the world's largest mosques and a key place of worship, notable for its large marble domes and beautiful gardens.",
    "liveurl": "https://www.youtube.com/embed/D9YjyHFy62U?si=MkVH53Sw2QUAVOFM",
    "color": "white"
},
{
    "id": "Hassan_II_Mosque",
    "name": "Hassan II Mosque",
    "shortDescription": "The largest mosque in Morocco, located in Casablanca.",
    "location": "Casablanca, Morocco",
    "religion": "Islam",
    "imageurl": "https://cdn.kimkim.com/files/a/images/bc6e3aaee81c7215e6493bc5120ee48ab86eb629/big-5ed6fa65c18c7cdabb3ec9f03081dd2a.jpg",
    "architectureImageURL": "https://i.redd.it/jpmph5q48bu61.jpg",
    "templeLogoURL": "https://cdn3.vectorstock.com/i/1000x1000/05/97/hassan-ii-mosque-in-morocco-flat-icon-vector-45960597.jpg",
    "briefDescription": "The Hassan II Mosque is the largest mosque in Morocco and is notable for its stunning architecture and the tallest minaret in the world.",
    "liveurl": "https://www.youtube.com/embed/7P8G1UnJDtQ?si=_VLc3moAvTqzdQnI",
    "color": "green"
},
{
    "id": "Faisal_Mosque",
    "name": "Faisal Mosque",
    "shortDescription": "The largest mosque in Pakistan, located in Islamabad.",
    "location": "Islamabad, Pakistan",
    "religion": "Islam",
    "imageurl": "https://mosqpedia.org/img/cache/largeimage/E7zPkew893EjHLpgd8S8lXYeLFWZprVakCqKBTFl",
    "architectureImageURL": "https://i.pinimg.com/originals/79/c0/3e/79c03e247fe63fefb1143cdc07f97a31.jpg",
    "templeLogoURL": "https://static.vecteezy.com/system/resources/thumbnails/018/811/856/small_2x/trendy-faisal-mosque-vector.jpg",
    "briefDescription": "Faisal Mosque is the largest mosque in Pakistan and is known for its unique, contemporary design and large prayer hall.",
    "liveurl": "https://www.youtube.com/embed/gfDhrRUilLE?si=mfHLKzrpvR4KTxxL",
    "color": "white"
},
{
    "id": "Quba_Mosque",
    "name": "Quba Mosque",
    "shortDescription": "The first mosque built in Islamic history, located in Medina.",
    "location": "Medina, Saudi Arabia",
    "religion": "Islam",
    "imageurl": "https://www.islamiclandmarks.com/wp-content/uploads/2016/01/Masjid-Quba-front.jpg",
    "architectureImageURL": "https://en.shafaqna.com/wp-content/uploads/2020/07/1766704_607.jpg",
    "templeLogoURL": "https://t4.ftcdn.net/jpg/07/51/41/95/360_F_751419545_zPdlxFX2LYuKlY8e3hNK9Ai019IUVHDh.jpg",
    "briefDescription": "The Quba Mosque is the first mosque built by Prophet Muhammad, situated in Medina. It is a place of great historical significance in Islam.",
    "liveurl": "https://www.youtube.com/embed/460i1OejiLw?si=HstWtZmU4EWaucX3",
    "color": "white"
},
{
    "id": "Jama_Masjid",
    "name": "Jama Masjid",
    "shortDescription": "One of the largest mosques in India, located in Delhi.",
    "location": "Delhi, India",
    "religion": "Islam",
    "imageurl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQauoRqQ8JGoEhlJA4gGcAeoGM3P--lNBiYetV4uScWzA&s",
    "architectureImageURL": "https://upload.wikimedia.org/wikipedia/commons/b/bd/Jama_Masjid%2C_Delhi%2C_mihrab_and_prayer_bay.jpg",
    "templeLogoURL": "https://cdn5.vectorstock.com/i/1000x1000/62/44/edification-islamic-mosque-jama-masjid-vector-26256244.jpg",
    "briefDescription": "The Jama Masjid of Delhi is one of the largest mosques in India, built by Mughal Emperor Shah Jahan.",
    "liveurl": "https://www.youtube.com/embed/y3HN_aMzedw?si=YywhL4MXGZ5mksEE",
    "color": "red and cream white"
},
{
    "id": "Shah_Mosque",
    "name": "Shah Mosque",
    "shortDescription": "A stunning example of Persian architecture, located in Isfahan.",
    "location": "Isfahan, Iran",
    "religion": "Islam",
    "imageurl": "https://upload.wikimedia.org/wikipedia/commons/8/8d/Isfahan_Royal_Mosque_general_%28retouched%29.jpg",
    "architectureImageURL": "https://wallpapers.com/images/hd/the-entry-gate-of-shah-mosque-pkjvn7wv4erog4gh.jpg",
    "templeLogoURL": "https://www.shutterstock.com/image-vector/vector-shah-mosque-isfahan-iran-260nw-1434814832.jpg",
    "briefDescription": "The Shah Mosque, also known as the Imam Mosque, is an iconic example of Persian architecture located in Isfahan, renowned for its exquisite tile work and grand scale.",
    "liveurl": "https://www.youtube.com/embed/R1xZurhSKuE?si=ZrWwBNi8KHfI-yb7",
    "color": "blue"
},
{
    "id": "Nasir_al-Mulk_Mosque",
    "name": "Nasir al-Mulk Mosque",
    "shortDescription": "Also known as the Pink Mosque, famous for its stained glass windows.",
    "location": "Shiraz, Iran",
    "religion": "Islam",
    "imageurl": "https://upload.wikimedia.org/wikipedia/commons/4/4b/Nasir_ol_Molk_Mosque_%2831233739431%29.jpg",
    "architectureImageURL": "https://img.atlasobscura.com/SO1qjcYW97H7FotOQqC83ATncBhhA_jjBOnVmeZi-n0/rs:fill:780:520:1/g:ce/q:81/sm:1/scp:1/ar:1/aHR0cHM6Ly9hdGxh/cy1kZXYuczMuYW1h/em9uYXdzLmNvbS91/cGxvYWRzL3BsYWNl/X2ltYWdlcy9iMzQ4/OTU3ZC04ZjQ5LTRj/ZTctYTIyMi0xMTdi/NTgxNWUyMmRkYTUy/YTI2ZTM3N2QzN2Jl/MjlfRzA5MkVFLmpw/Zw.jpg",
    "templeLogoURL": "https://i.etsystatic.com/40616180/r/il/d7ae5f/4752486440/il_300x300.4752486440_cljj.jpg",
    "briefDescription": "The Nasir al-Mulk Mosque, also known as the Pink Mosque, is famous for its stunning stained glass windows and intricate tile work, creating a kaleidoscope of colors in the morning sunlight.",
    "liveurl": "https://www.youtube.com/embed/rQLF_i43Kac?si=Pa7641ufRFpbe4Cl",
    "color": "pink"
},
{
    "id": "Sheikh_Lotfollah_Mosque",
    "name": "Sheikh Lotfollah Mosque",
    "shortDescription": "A masterpiece of Iranian architecture, located in Isfahan.",
    "location": "Isfahan, Iran",
    "religion": "Islam",
    "imageurl": "https://irandoostan.com/dostcont/uploads/2018/05/Sheikh-Lotfollah-Mosque2-1.jpg",
    "architectureImageURL": "https://media-cdn.tripadvisor.com/media/photo-m/1280/1c/d4/c8/dd/sheikh-lotfollah-mosque.jpg",
    "templeLogoURL": "https://www.shutterstock.com/image-vector/sheikh-lotfollah-mosque-iran-600w-1032520099.jpg",
    "briefDescription": "The Sheikh Lotfollah Mosque is a stunning masterpiece of Iranian architecture, known for its intricate tile work and unique dome, located on the Naqsh-e Jahan Square in Isfahan.",
    "liveurl": "https://www.youtube.com/embed/uOd3B5ZhZXk?si=KoYeHOKfqgx_tLBz",
    "color": "cream"
}


  // {
  //   "id": "Jama_Masjid",
  //   "name": "Jama Masjid",
  //   "shortDescription": "One of the largest mosques in India, built by Mughal Emperor Shah Jahan.",
  //   "location": "Delhi",
  //   "religon": "Islam",
  //   "imageurl": "https://i.pinimg.com/474x/a9/31/61/a93161f952f86a8673e5be5b65b004f6.jpg",
  //   "arcitectureImageURL": "https://in.pinterest.com/pin/722475965235967844/",
  //   "tempelLogoURL": "https://i.pinimg.com/474x/1f/8d/6a/1f8d6a2d6b2587aad0d467566c90db7b.jpg",
  //   "briefDescription": "Jama Masjid is one of the largest and best-known mosques in India. It was built by Mughal Emperor Shah Jahan between 1644 and 1656. The mosque is constructed with red sandstone and white marble and can accommodate up to 25,000 worshippers. It is located in the heart of Old Delhi.",
  //   "liveurl": "https://www.youtube.com/embed/32yenT6ai3E",
  //   "color": "white"

    
  // },
  // {
  //   "id": "Mecca_Masjid",
  //   "name": "Mecca Masjid",
  //   "shortDescription": "One of the oldest mosques in Hyderabad, Telangana.",
  //   "location": "Hyderabad",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Mecca Masjid is one of the oldest mosques in Hyderabad, Telangana, India. It is one of the largest masjids in India and is listed as a heritage building in the old city of Hyderabad.",
  //   "liveurl": "",
  //   "color": "green"
  // },
  // {
  //   "id": "Taj_ul_Masajid",
  //   "name": "Taj-ul-Masajid",
  //   "shortDescription": "One of the largest mosques in Asia.",
  //   "location": "Bhopal",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Taj-ul-Masajid is one of the largest mosques in Asia. Its construction was initiated during the reign of the Mughal Emperor Bahadur Shah Zafar by Nawab Shah Jahan Begum of Bhopal.",
  //   "liveurl": "",
  //   "color": "blue"
  // },
  // {
  //   "id": "Nagina_Masjid",
  //   "name": "Nagina Masjid",
  //   "shortDescription": "An ancient mosque built during the Mughal era.",
  //   "location": "Agra",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Nagina Masjid is an ancient mosque located within the premises of the Agra Fort in Agra, India. It was built during the Mughal era and is known for its beautiful architecture.",
  //   "liveurl": "",
  //   "color": "white"
  // },
  // {
  //   "id": "Babri_Masjid",
  //   "name": "Babri Masjid",
  //   "shortDescription": "A mosque in Ayodhya, India, demolished in 1992.",
  //   "location": "Ayodhya",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Babri Masjid was a mosque in Ayodhya, India, which was demolished in 1992. The demolition led to widespread communal riots across India and significantly impacted Indian politics.",
  //   "liveurl": "",
  //   "color": "red"
  // },
  // {
  //   "id": "Nakhoda_Masjid",
  //   "name": "Nakhoda Masjid",
  //   "shortDescription": "A grand mosque in Kolkata, West Bengal.",
  //   "location": "Kolkata",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Nakhoda Masjid is a grand mosque located in Kolkata, West Bengal. It was built in the early 20th century and is one of the largest mosques in Kolkata.",
  //   "liveurl": "",
  //   "color": "green"
  // },
  // {
  //   "id": "Haji_Ali_Dargah",
  //   "name": "Haji Ali Dargah",
  //   "shortDescription": "A mosque and dargah located in Mumbai, Maharashtra.",
  //   "location": "Mumbai",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Haji Ali Dargah is a mosque and dargah located on an islet off the coast of Worli in Mumbai, Maharashtra. It is one of the most recognizable landmarks of Mumbai.",
  //   "liveurl": "",
  //   "color": "blue"
  // },
  // {
  //   "id": "Badi_Masjid",
  //   "name": "Badi Masjid",
  //   "shortDescription": "A historic mosque in Jaipur, Rajasthan.",
  //   "location": "Jaipur",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Badi Masjid is a historic mosque located in Jaipur, Rajasthan. It was built by Mughal Emperor Aurangzeb and is known for its grandeur and architectural beauty.",
  //   "liveurl": "",
  //   "color": "white"
  // },
  // {
  //   "id": "Hazratbal_Shrine",
  //   "name": "Hazratbal Shrine",
  //   "shortDescription": "A shrine and mosque located in Srinagar, Jammu and Kashmir.",
  //   "location": "Srinagar",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Hazratbal Shrine is a shrine and mosque located in Srinagar, Jammu and Kashmir. It is considered one of the holiest shrines in Kashmir and houses a relic believed to be a hair of the Islamic prophet Muhammad.",
  //   "liveurl": "",
  //   "color": "green"
  // },
  // {
  //   "id": "Baitul_Mukarram",
  //   "name": "Baitul Mukarram",
  //   "shortDescription": "The national mosque of Bangladesh, located in Dhaka.",
  //   "location": "Dhaka",
  //   "religon": "Islam",
  //   "imageurl": "",
  //   "arcitectureImageURL": "",
  //   "tempelLogoURL": "",
  //   "briefDescription": "Baitul Mukarram is the national mosque of Bangladesh, located in the heart",
  //   "liveurl": "",
  //   "color": "yellow"
  // }
  ]

export default masjids