const festivals = [
    // { name: "New Year's Day", date: "January 1" },
    // { name: "Makar Sankranti", date: "January 14" },
    // { name: "Republic Day", date: "January 26" },
    // { name: "Valentine's Day", date: "February 14" },
    // { name: "Maha Shivaratri", date: "March 8" },
    // { name: "Holi", date: "March 25" },
    // { name: "Ram Navami", date: "April 17" },
    // { name: "Good Friday", date: "March 29" },
    // { name: "Easter", date: "March 31" },
    // { name: "Earth Day", date: "April 22" },
    // { name: "Labor Day", date: "May 1" },
    // { name: "Eid al-Fitr", date: "April 10" },
    // { name: "Mother's Day", date: "May 12" },
    // { name: "Father's Day", date: "June 16" },
    // { name: "Eid al-Adha", date: "June 17" },
    { name: "Raksha Bandhan", date: "August 19" },
    { name: "Independence Day", date: "August 15" },
    { name: "Janmashtami", date: "August 26" },
    { name: "Ganesh Chaturthi", date: "September 7" },
    { name: "Gandhi Jayanti", date: "October 2" },
    { name: "Dussehra", date: "October 13" },
    { name: "Karva Chauth", date: "October 20" },
    // { name: "Halloween", date: "October 31" },
    { name: "Diwali", date: "November 1" },
    { name: "Govardhan Puja", date: "November 2" },
    { name: "Bhai Dooj", date: "November 3" },
    // { name: "Guru Nanak Jayanti", date: "November 15" },
    // { name: "Thanksgiving", date: "November 28" },
    // { name: "Christmas", date: "December 25" },
    // { name: "Hanukkah", date: "December 25" },
    { name: "Chinese New Year", date: "February 10" },
    // { name: "Ramadan", date: "March 10" }
];

export default festivals